### PR TITLE
allow for non-integer omeag steps

### PR DESCRIPTION
**Pull request by AxelHenningsson**

### CODE REVIEW

**Comment by AxelHenningsson** [comment]
allow for non-integer omeag steps

**Comment by jonwright** [comment]
I am assuming you can merge this yourself, but let me know if there is some missing permission. Somewhere in the sinogram builders we use integer omega steps, but I don't think you are looking at that.

**Comment by AxelHenningsson** [comment]
Only write access can merge. This is just one line for the s3dxrd simulation code and does not affect any other parts.

**Comment by jonwright** [comment]
Hopefully the permission is fixed now? Let me know if it doesn't merge for you yet...

**Comment by AxelHenningsson** [comment]
Thx :)

**Pull request merged**
